parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/functions.php'

    # Controllers
    App\Api\Controller\:
        resource: '../src/Api/Controller'
        tags: ['controller.service_arguments']

    ################################
    # API
    ################################
    app.api.serializer:
        class: Symfony\Component\Serializer\SerializerInterface
        factory: ['@App\Api\Infrastructure\Request\ApiRequestSerializerFactory', 'create']

    App\Api\Infrastructure\Request\SendRequestToBankResolver:
        arguments:
            $serializer: '@app.api.serializer'

    ################################
    # Rabbit connection
    ################################
    App\Infrastructure\Transport\Connection\RabbitConnection:
        class: App\Infrastructure\Transport\Connection\PhpAmqpLibConnection
        arguments:
            $host: '%env(RABBIT_HOST)%'
            $port: '%env(int:RABBIT_PORT)%'
            $user: '%env(RABBIT_USER)%'
            $password: '%env(RABBIT_PASSWORD)%'
